
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace HPing {
    using System;
    using Terminal.Gui;
    using Terminal.Gui.App;
    using Terminal.Gui.Drawing;
    using Terminal.Gui.Input;
    using Terminal.Gui.ViewBase;
    using Terminal.Gui.Views;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class SingleView : Terminal.Gui.Views.Window {
        
        private Terminal.Gui.Views.GraphView graphView;
        
        private Terminal.Gui.Views.ListView listView;
        
        private void InitializeComponent() {
            this.listView = new Terminal.Gui.Views.ListView();
            this.graphView = new Terminal.Gui.Views.GraphView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Overlapped;
            this.CanFocus = true;
            this.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "";
            this.graphView.Width = Dim.Percent(100);
            this.graphView.Height = Dim.Percent(50);
            this.graphView.X = 0;
            this.graphView.Y = 0;
            this.graphView.Visible = true;
            this.graphView.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.graphView.CanFocus = true;
            this.graphView.ShadowStyle = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.graphView.Data = "graphView";
            this.graphView.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.graphView.GraphColor = new Terminal.Gui.Drawing.Attribute(Terminal.Gui.Drawing.Color.White,Terminal.Gui.Drawing.Color.Black);
            this.graphView.ScrollOffset = new System.Drawing.PointF(0F, 0F);
            this.graphView.MarginLeft = 0u;
            this.graphView.MarginBottom = 0u;
            this.graphView.CellSize = new System.Drawing.PointF(1F, 1F);
            this.graphView.AxisX.Visible = true;
            this.graphView.AxisX.Increment = 1F;
            this.graphView.AxisX.ShowLabelsEvery = 5u;
            this.graphView.AxisX.Minimum = null;
            this.graphView.AxisX.Text = null;
            this.graphView.AxisY.Visible = true;
            this.graphView.AxisY.Increment = 1F;
            this.graphView.AxisY.ShowLabelsEvery = 5u;
            this.graphView.AxisY.Minimum = null;
            this.graphView.AxisY.Text = null;
            this.Add(this.graphView);
            this.listView.Width                   = Dim.Percent(100);
            this.listView.Height                  = Dim.Percent(49);
            this.listView.X                       = 0;
            this.listView.Y                       = 30;
            this.listView.Visible                 = true;
            this.listView.Arrangement             = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.listView.CanFocus                = true;
            this.listView.ShadowStyle             = Terminal.Gui.ViewBase.ShadowStyle.None;
            this.listView.Data                    = "listView";
            this.listView.TextAlignment           = Terminal.Gui.ViewBase.Alignment.Start;
            this.listView.Source                  = new Terminal.Gui.Views.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] { }));
            this.listView.AllowsMarking           = false;
            this.listView.AllowsMultipleSelection = true;
            this.Add(this.listView);
        }
    }
}
