//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using HPing.Rules;
using HPing.Rules.Single;
using HPing.Utils;
using Juyi.Types;
using Terminal.Gui.App;
using Terminal.Gui.ViewBase;

namespace HPing {
    using Terminal.Gui;

    /// <summary>
    /// PING单个地址的界面
    /// </summary>
    public partial class SingleView {
        private readonly SingleGraphView       singleGraphView;
        private readonly SinglePingRule        singlePingRule;
        private readonly DescFixedSizeLinkedList<string> result = new DescFixedSizeLinkedList<string>(100);

        public SingleView() {
            InitializeComponent();
            singleGraphView = new SingleGraphView(graphView);

            var target = GetTarget();
            this.Title = $"HPing - {target}  , 按 {Application.QuitKey} 退出";

            singlePingRule         =  new SinglePingRule(target);
            singlePingRule.OnPing  += SinglePingRuleOnOnPing;
            singlePingRule.OnError += SinglePingRuleOnOnError;
            singlePingRule.Run();

            GlobalSummary.Init();

            this.listView.Y = Pos.Bottom(graphView) + 1;
            this.SetNeedsDraw();
        }

        private static string GetTarget() {
            return ArgumentManager.Current!.Target;
        }


        private void SinglePingRuleOnOnError(Exception obj) {
            GlobalSummary.Fail();

            var str = $"{Utils.Utils.FormatTime(DateTime.Now)}  : 错误 -> {obj.Message}";
            result.Add(str);
            var aa = new ObservableCollection<string>(result.Items);
            listView.SetSourceAsync(aa);
        }

        private void SinglePingRuleOnOnPing(PingReply reply) {
            GlobalSummary.Add(reply);

            //     Console.WriteLine ("Address: {0}",        reply.Address.ToString ());
            //     Console.WriteLine ("RoundTrip time: {0}", reply.RoundtripTime);
            //     Console.WriteLine ("Time to live: {0}",   reply.Options.Ttl);
            //     Console.WriteLine ("Don't fragment: {0}", reply.Options.DontFragment);
            //     Console.WriteLine ("Buffer size: {0}",    reply.Buffer.Length);

            //var sb = new StringBuilder();
            // sb.AppendLine($"Address: {reply.Address}");
            // sb.AppendLine($"RoundTrip time: {reply.RoundtripTime}");
            // sb.AppendLine($"Time to live: {reply.Options.Ttl}");
            // sb.AppendLine($"Don't fragment: {reply.Options.DontFragment}");
            // sb.AppendLine($"Buffer size: {reply.Buffer.Length}");

            string str = "";
            if (ArgumentManager.Current!.IsUseCustomPayload) {
                str = $"{DateTime.Now:h:mm:ss}  : 来自 {reply.Address} 的回复: 字节={reply.Buffer.Length} 时间={reply.RoundtripTime}ms TTL={reply.Options.Ttl}";
            }
            else {
                str = $"{Utils.Utils.FormatTime(DateTime.Now)}  : 来自 {reply.Address} 的回复: 时间={reply.RoundtripTime}ms ";
            }

            result.Add(str);

            var aa = new ObservableCollection<string>(result.Items);

            listView.SetSourceAsync(aa);

            singleGraphView.Update(reply.RoundtripTime);
        }
    }
}